name: Build

on:
  push:
    branches:
      - main
    paths:
      - "scripts/**.py"
      - "scripts/pyproject.toml"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  check:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.8.0
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: scripts/setup.py

      - name: Build and check wheel
        run: |
          pip install build twine
          python -m build scripts
          twine check scripts/dist/*
